version: '3.8'

services:
  hubspot-app:
    container_name: hubspot-app
    build:
      context: .
      dockerfile: Dockerfile
    image: hubspot-app:0.0.2
    volumes:
      - .:/hubspot-app
      - ./node_modules:/hubspot-app/node_modules
    ports:
      - 5001:5001
    environment:
      - CHOKIDAR_USEPOLLING=true
