version: '3.8'

services:
  vue_app:
    container_name: vue_app
    build:
      context: .
      dockerfile: Dockerfile
    image: vue_app:0.0.2
    volumes:
      - '.:/vue-app'
      - '/vue-app/node_modules'
    ports:
      - 5000:5000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - ufp_network

networks:
  ufp_network:
    external:
      name: ufp_network