export const messages = {
	en: {
	  message: {
		myboard: 'Board',
		stats: 'Stats',
		match: 'Match',
		player: 'Player',
		Documents: 'Documents',
		users: 'Users',
		allUsers: 'All Users',
		addNewUser: 'Add New User',
		ufpNews: 'UFP News',
		Emails: 'Emails',
		Footballnews: 'Football News',
		NewsRumors: 'News & Rumors',
		Settings: 'Settings',
		Groups: 'Groups',
		Products: 'Products',
		Surveys: 'Surveys',
		Contact: 'Contact',
		ForgotPassword: 'Forgot Password',
		Login: 'Log In',
		LoginV: 'Log In',
		Submit: 'Submit',
		Password: 'Password',
		password: 'password',
		ForgotPasswordNotice: 'Input your email and we will send you reset password link.',
		EmailRequired: 'Email is Required.',
		EmailNotValid: 'Email is not valid.',
		UpdatePassword: 'Update Password',
		NewPassword: 'New Password',
		ConfirmNewPassword: 'Confirm New Password',
		PickAPassword: 'Pick a password',
		Suggestions: 'Suggestions',
		Atleast: 'At least',
		oneIt: 'one',
		lowercase: 'lowercase',
		uppercase: 'uppercase',
		numeric: 'numeric',
		characters: 'characters',
		Update: 'Update',
		Nonewemails: 'No new emails',
		Inbox: 'Inbox',
		Profile: 'Profile',
		Wallet: 'Wallet',
		Logout: 'Logout',
		MatchStats: 'Match Stats',
		Season: 'Season',
		Match: 'Match',
		SelectMatch: 'Select Match',
		SelectSeason: 'Select Season',
		Playerstats: 'Player stats',
		Matches: 'Matches',
		Minutesplayed: 'Minutes played',
		Goals: 'Goals',
		Yellowcards: 'Yellow cards',
		Redcards: 'Red cards',
		LINEUPS: 'LINEUPS',
		STATS: 'STATS',
		TEAM: 'TEAM',
	  },
	  validations: {
        required: "This field is required.",
        email: "Please enter a valid email address.",
		minLength: "Minimum length is 8 characters",
		sameAs: "Passwords don't match"
      },
	},
	sk: {
	  message: {
		myboard: 'Nástenka',
		stats: 'Štatistiky',
		match: 'Zápas',
		player: 'Hráč',
		Documents: 'Dokumenty',
		users: 'Používatelia',
		allUsers: 'Zoznam Používateľov',
		addNewUser: 'Pridať Používateľa',
		ufpNews: 'Správy UFP',
		Emails: 'Emaily',
		Footballnews: 'Futbalové správy',
		NewsRumors: 'Správy a Novinky',
		Settings: 'Nastavenia',
		Groups: 'Skupiny',
		Products: 'Produkty',
		Surveys: 'Dotazníky',
		Contact: 'Kontakt',
		ForgotPassword: 'Zabudnuté heslo',
		Login: 'Prihlásenie',
		LoginV: 'Prihlásiť',
		Submit: 'Poslať',
		Password: 'Heslo',
		password: 'heslo',
		ForgotPasswordNotice: 'Vložte sem Váš prihlasovací email, na ktorý pošleme link na reset hesla.',
		EmailRequired: 'Email je potrebný.',
		EmailNotValid: 'Email nie je platný.',
		UpdatePassword: 'Zmena hesla.',
		NewPassword: 'Nové heslo',
		ConfirmNewPassword: 'Potvrdenie nového hesla',
		PickAPassword: 'Výber hesla',
		Suggestions: 'Návrhy',
		Atleast: 'Aspoň',
		oneIt: 'jedno',
		lowercase: 'malé písmeno',
		uppercase: 'veľké písmeno',
		numeric: 'číslo',
		characters: 'písmen',
		Update: 'Aktualizovať',
		Nonewemails: 'Žiadne nové správy',
		Inbox: 'Schránka',
		Profile: 'Profil',
		Wallet: 'Peňaženka',
		Logout: 'Odhlásenie',
		MatchStats: 'Zápasové štatistiky',
		Season: 'Sezóna',
		Match: 'Zápas',
		SelectMatch: 'Vyberte Zápas',
		SelectSeason: 'Vyberte Sezónu',
		Playerstats: 'Štatistiky hráča',
		Matches: 'Zápasy',
		Minutesplayed: 'Odohrané minúty',
		Goals: 'Góly',
		Yellowcards: 'Žlté karty',
		Redcards: 'Červené karty',
		LINEUPS: 'ZOSTAVY',
		STATS: 'ŠTATISTIKY',
		TEAM: 'TÍM',
	  },
	  validations: {
        required: "Toto pole je nevyhnutné.",
        email: "Vložte platný email.",
		minLength: `Minimálna dĺžka je 8 znakov {minLength}`,
		sameAs: `Heslá sa nezhodujú`,
      },
	}
  }