export const messages = {
	en: {
		message: {
			myboard: 'Board',
			stats: 'Stats',
			match: 'Match',
			player: 'Player',
			Documents: 'Documents',
			users: 'Users',
			usersov: 'Users',
			allUsers: 'All Users',
			addNewUser: 'Add New User',
			ufpNews: 'UFP News',
			Emails: 'Emails',
			emailov: 'Emails',
			Footballnews: 'Football News',
			NewsRumors: 'News & Rumors',
			Settings: 'Settings',
			Groups: 'Groups',
			Products: 'Products',
			Surveys: 'Surveys',
			Contact: 'Contact',
			ForgotPassword: 'Forgot Password',
			Login: 'Log In',
			LoginV: 'LOG IN',
			Submit: 'Submit',
			Password: 'Password',
			password: 'password',
			ForgotPasswordNotice: 'Please provide your email address, to which we will send a link for password reset.',
			EmailRequired: 'Email is Required.',
			EmailNotValid: 'Email is not valid.',
			UpdatePassword: 'Update Password',
			NewPassword: 'New Password',
			ConfirmNewPassword: 'Confirm New Password',
			PickAPassword: 'Pick a password',
			Suggestions: 'Suggestions',
			Atleast: 'At least',
			oneIt: 'one',
			lowercase: 'lowercase',
			uppercase: 'uppercase',
			numeric: 'numeric',
			characters: 'characters',
			Update: 'Update',
			Nonewemails: 'No new emails',
			Inbox: 'Inbox',
			Profile: 'Profile',
			Wallet: 'Wallet',
			Logout: 'Logout',
			MatchStats: 'Match Stats',
			Season: 'Season',
			Match: 'Match',
			SelectMatch: 'Select Match',
			SelectSeason: 'Select Season',
			Playerstats: 'Player stats',
			Matches: 'Matches',
			Minutesplayed: 'Minutes played',
			Goals: 'Goals',
			Goal: 'Goal',
			Yellowcards: 'Yellow cards',
			Redcards: 'Red cards',
			LINEUPS: 'LINEUPS',
			Lineups: 'Lineups',
			STATS: 'STATS',
			Stats: 'Stats',
			TEAM: 'TEAM',
			Substitutes: 'Substitutes',
			BallPossession: 'Ball Possession',
			PurePossessionTime: 'Pure possession time',
			AvgPossessionTime: 'Average possession time',
			Shotsontarget: 'Shots On Target',
			Completedpasses: 'Completed passes',
			TotalAttempts: 'Total Attempts',
			Fouls: 'Fouls',
			Corners: 'Corners',
			Offsides: 'Offsides',
			Freekicks: 'Freekicks',
			FreeKicksOnTarget: 'Free kicks on target',
			DirectFreeKicks: 'Free kicks on target',
			DirectFreeKicksOnTarget: 'Free kicks on target',
			Successfulduels: 'Successful duels',
			Totallooses: 'Total Looses',
			LossesHigh: 'Losses in the attacking zone',
			LossesMedium: 'Losses in the midfield',
			LossesLow: 'Losses in the defensive zone',
			OwnHalfLooses: 'Own half looses',
			DangerousOwnHalfLooses: 'Dangerous own half looses',
			Successfulpasses: 'Successful Passes',
			Shots: 'Shots',
			Shot: 'Shot',
			Duels: 'Duels',
			Passes: 'Passes',
			AerialDuels: 'Aerial duels',
			AerialDuelsSuccessful: 'Aerial successful duels',
			FieldAerialDuels: 'Fiels aerial duels',
			DefensiveDuels: 'Defensive duels',
			OffensiveDuels: 'Offensive duels',
			PressingDuels: 'Pressing duels',
			BackPasses: 'Back passes',
			BackPassesSuccessful: 'Back passes successful',
			ForwardPasses: 'Forward Passes',
			ForwardPassesSuccessful: 'Forward passes successful',
			VerticalPasses: 'Vertical passes',
			VerticalPassesSuccessful: 'Vertical passes successful',
			ShotAssists: 'Shot assists',
			SecondAssists: 'Second assists',
			BlockedShots: 'Blocked shots',
			BlockedShot: 'Blocked shot',
			Crosses: 'Crosses',
			CrossesSuccessful: 'Crosses successful',
			CrossesBlocked: 'Crosses blocked',
			CrossesLow: 'Crosses low',
			CrossesHigh: 'Crosses high',
			FoulsSuffered: 'Fouls suffered',
			Dribbles: 'Dribbles',
			ReceivedPasses: 'Received Passes',
			Losses: 'Losses',
			AttackingActions: 'Attacking Actions',
			DefensiveActions: 'Defensive Actions',
			KeywordSearch: 'Keyword Search',
			ClearFilters: 'Clear Filters',
			Name: 'Name',
			Surname: 'Surname',
			Select: 'Select',
			Club: 'Club',
			Fee: 'Fee',
			State: 'State',
			Activity: 'Activity',
			Showing: 'Showing',
			to: 'to',
			To: 'To',
			of: 'of',
			SelectanAction: 'Select an Action',
			SendEmail: 'Send Email',
			AssignGroup: 'Assign Group',
			DetachGroup: 'Detach Group',
			EmailEditor: 'Email Editor',
			SelectGroup: 'Select Group',
			Choosed: 'Choosed',
			Choose: 'Choose',
			PaymentMethod: 'Payment Method',
			PaymentMethodN: 'Payment Method',
			CreditDebitCard: 'Credit/Debit card',
			Continue: 'Continue',
			Noemailsfound: 'No emails found.',
			Address: 'Address',
			Subject: 'Subject',
			Date: 'Date',
			DeleteEmails: 'Delete Emails',
			Nouserschosen: 'No users chosen.',
			Noemailschosen: 'No emails chosen.',
			Contactus: 'Contact us',
			Insertmessage: 'Insert message',
			SelectRecipient: 'Select Recipient',
			UserData: 'User Data',
			Code: 'Code',
			Phonenumber: 'Phone number',
			Change: 'Change',
			Olde: 'Old',
			Newe: 'New',
			Confirm: 'Confirm',
			Confirmation: 'Confirmation',
			Language: 'Language',
			Yearly: 'Yearly',
			fee: 'fee',
			Membership: 'Membership',
			MemberFrom: 'Member From',
			member: 'member',
			Active: 'Active',
			Inactive: 'Inactive',
			Active: 'active',
			Paid: 'Paid',
			Unpaid: 'Unpaid',
			Notregistered: 'Not registered',
			Create: 'CREATE',
			Account: 'ACCOUNT',
			Register: 'Register',
			RegisterV: 'REGISTER',
			ConfirmPassword: 'Confirm Password',
			Youraccountisregisteredundername: 'Your account is registered under name:',
			andemail: 'and we have sent verify link on your email:',
			Alreadyaccount: 'Already have account',
			GlobalNews: 'Global News',
			SelectaRole: 'Select a Role',
			Generate: 'Generate',
			Inordertoviewyourstatistics: 'In order to view your statistics, you need to select the desired match first.',
			PERSONAL: 'PERSONAL',
			OnTarget: 'On Target',
			OffTarget: 'Off Target',
			Successful: 'Successful',
			Failed: 'Failed',
			Other: 'Other',
			ThisSeason: 'This season',
			WeProtectIntro: 'We protect your football interests',
			WelcomeIntro: 'Welcome to the official app of the Union of Football Professionals in Slovakia.',
			Options: 'Options',
			WithoutClub: 'Without Club',
			OtherClub: 'Other Club',
			Myclubis: 'My club is',
			NameOfClub: 'Name of club',
			AgreeToTerms: 'By creating an account, you agree to our',
			TermsOfUse: 'Terms of Use',
			TermsOfUseN: 'Terms of Use',
			and: 'and',
			PrivacyPolicy: 'Privacy Policy',
			PrivacyPolicyN: 'Privacy Policy',
			Templates: 'Templates',
			AddTo: 'Add to',
			Add: 'Add',
			Start: 'Start',
			End: 'End',
			template: 'template',
			Title: 'Title',
			Save: 'Save',
			ReviewAll: 'Review all your individual statistics.',
			ReviewAlldesc: 'Explore all your personal statistics from the wyscout and discover how you have performed in individual matches or seasons.',
			Allthenews: 'All the news from the UFP in one application.',
			Allthenewsdesc: 'Follow all the activities of the UFP and its activites within a simple and convenient application.',
			FastConnection: 'Fast connection directly with the UFP.',
			FastConnectionDesc: 'Connect with UFP directly within an app and consult your needs and problems whenever they occur.',
			SimplePayment: 'Simple payment of membership fee and overview of payment history.',
			SimplePaymentDesc: 'Pay your membership fees easily using a credit card, Apple Pay, or Google Pay. A hassle-free way to become a UFP member.',
			SurveysInvolved: 'Get involved in voting and surveys within the UFP.',
			SurveysInvolvedDesc: 'As a member of the UFP, you have the opportunity to participate in UFP voting and respond to surveys conducted by the UFP.',
			Skip: 'Skip',
			SettingUpNotif: 'Setting up notifications',
			SettingUpNotifDesc: 'You can modify the notification settings at any time in your account settings.',
			TurnOnNotif: 'TURN ON NOTIFICATIONS',
			NotNow: 'NOT NOW',
			MembershipDesc: 'By subscribing, you will have an access to app features including personal statistics, team statistics, legal support from UFP lawyers, benefits from UFP partners and much more! (The specific features you receive will depend on the package you select)',
			Help: 'Help',
			Board: 'Board',
			AddGroup: 'Add Group',
			AddEmails: 'Add Emails',
			Order: 'Order',
			Emails: 'Emails',
			Members: 'Members',
			AddMembers: 'Add members',
			Position: 'Position',
			Description: 'Description',
			Image: 'Image',
			GroupS: 'group',
			Addp: 'Add',
			Question: 'Question',
			Answer: 'Answer',
			SendAnonymously: 'Send message anonymously',
			AnonymousNotice: "*Don't worry, we truly won't receive any information about you, and we can't figure out who sent the message. However, please keep in mind that we won't be able to reply to your message since we don't know who it's from.",
			Payments: "Payments",
			Payment: "Payment",
			ProfileNotice: "Edit your profile information",
			PaymentsNotice: "See your current and previous payments",
			LogoutNotice: "Logout from application",
			Notifications: "Notifications",
			NotificationsNotice: "Get alerted for important events",
			LanguageNotice: "Edit your language preferences",
			English: "English",
			Slovak: "Slovak",
			DateOfPayment: "Date of payment",
			Subscription: "Subscription",
			DateOfStart: "Date of start",
			NextBillingDate: "Next billing date",
			Cancel: "Cancel",
			General: "General",
			News: "News",
			posts: "posts",
			No: "No",
			More: "More",
			Share: "Share",
			MissedNews: "You may have missed...",
			Player: "Player",
			PLAYER: "PLAYER",
			PersonalTeam: "Personal & Team",
			MembershipFee: 'Membership Fee',
			PlayerProfile: 'Player Profile',
			Events: 'Events',
			Media: 'Media',
			Podcasts: 'Podcasts',
			Agency: 'Agency',
			CategoryU: 'Category',
			Men: 'Men',
			Women: 'Women',
			Gender: 'Gender',
			Goalkeeper: 'Goalkeeper',
			Defenders: 'Defenders',
			Defender: 'Defender',
			Midfielders: 'Midfielders',
			Midfielder: 'Midfielder',
			Strikers: 'Strikers',
			Striker: 'Striker',
			UploadImage: 'Upload Image',
			PaymentPeriod: 'Payment period',
			Monthly: 'Monthly',
			Yearly: 'Yearly',
			month: 'month',
			year: 'year',
			YearlyPaymentNotice: 'The payment is made on an annual basis, covering the calendar year from 1.7. to 30.6.',
			yourplan: 'your plan',
			Basic: 'Basic',
			Premium: 'Premium',
			PAY: 'PAY',
			Pay: 'Pay',
			Includes: 'Includes',
			MatchReports: 'Match reports',
			Personal: 'Personal',
			MatchVideos: 'Match videos',
			ComparisonWithOthers: 'Comparison with other players',
			StatsOfOthers: 'Statistics & Videos of other players',
			RequireAction: 'Wait for automatic safe redirection.',
			PROCEEDTOPAYMENT: 'PROCEED TO PAYMENT',
			NotPaidNotice: 'Your membership fee has not been paid.',
			NotPaidNotice2: 'To regain access to your account, it is necessary to pay a membership fee.',
			FeeFinishDate: 'Fee finish date',
			Country: 'Country',
			Age: 'Age',
			Number: 'Number',
			YourLastGames: 'Your last games',
			SeeMore: 'See more',
			YourMatchStats: 'Your match stats',
			YourSeasonStats: 'Your season stats',
			KEYSTATS: 'KEY STATS',
			DISTRIBUTION: 'DISTRIBUTION',
			ATTACKING: 'ATTACKING',
			DEFENDING: 'DEFENDING',
			DUELS: 'DUELS',
			Duel: 'Duel',
			DISCIPLINARY: 'DISCIPLINARY',
			PASSES: 'PASSES',
			MatchEvents: 'Match events',
			Pass: 'Pass',
			PassTime: 'Pass time',
			PassAccuracy: 'Pass accuracy',
			PassLength: 'Pass length',
			PassType: 'Pass type',
			PassRecipient: 'Pass recipient',
			PlayerComparison: 'Player comparison',
			SearchPlayer: 'Search for a player',
			Coach: 'Coach',
			Attack: 'Attack',
			Defence: 'Defence',
			Transitions: 'Transitions',
			Assists: 'Assists',
			SmartPasses: 'Smart passes',
			Successful: 'Successful',
			Unsuccessful: 'Unsuccessful',
			PassesToFinalThird: 'Passes to final third',
			PassesToFinalThirdSuccessful: 'Passes to final third successful',
			ThroughPasses: 'ThroughPasses',
			ThroughPassesSuccessful: 'Through passes successful',
			KeyPasses: 'Key passes',
			KeyPassesSuccessful: 'Key passes successful',
			LongPasses: 'Long passes',
			LongPassesSuccessful: 'Long passes successful',
			ProgressivePasses: 'Progressive passes',
			ProgressivePassesSuccessful: 'Progressive passes successful',
			LateralPasses: 'Lateral passes',
			LateralPassesSuccessful: 'Lateral passes successful',
			TouchInBox: 'Touch in box',
			ProgressiveRun: 'Progressive run',
			HeadShots: 'Head shots',
			Penalties: 'Penalties',
			ThirdAssists: 'Third assists',
			ShotOnTargetAssists: 'Shot on target sssists',
			MissedBalls: 'Missed balls',
			LinkupPlays: 'Linkup plays',
			Accelerations: 'Accelerations',
			Interceptions: 'Interceptions',
			Recoveries: 'Recoveries',
			RecoveriesHigh: 'Recoveries in the attacking zone',
			RecoveriesMedium: 'Recoveries in the midfield',
			RecoveriesLow: 'Recoveries in the defensive zone',
			OpponentHalfRecoveries: 'Opponent half recoveries',
			DangerousOpponentHalfRecoveries: 'Dangerous Opponent half recoveries',
			SlidingTackles: 'Sliding tackles',
			Clearances: 'Clearances',
			LooseBallDuels: 'Loose ball duels',
			LooseBallDuelsSuccessful: 'Loose ball successful duels',
			DirectRedCards: 'Direct red cards',
			UpgradeMembership: 'Upgrade membership to',
			Surcharge: 'Surcharge',
			UpgradeProduct: 'Upgrade product',
			from: 'from',
			to: 'to',
			response: 'response',
			All: 'All',
			English: 'English',
			Slovak: 'Slovak',
			ForgotYour: 'Forgot your',
			EnterEmail: 'Enter your email address',
			SelectFrom: 'Select from number',
			SelectTo: 'to',
			ShotsOutsideBox: 'Shots outside the box',
			ShotsOutsideBoxOnTarget: 'Shots outside the box on target',
			ShotsOnPost: 'Shots on post',
			ShotsWide: 'Shots wide',
			ShotsFromBox: 'Shots from box',
			ShotsFromDangerZone: 'Shots from danger zone',
			PlayerDetails: 'Player details',
			PassesToPenalty: 'Passes to penalty',
			PassesToPenaltySuccessful: 'Successful passes to penalty',
			ThrowIns: 'Throw ins',
			RightThrowIns: 'Right throw ins',
			LeftThrowIns: 'Left throw ins',
			ReachingOpponentHalf: 'Reaching opponent half',
			ReachingOpponentBox: 'Reaching opponent box',
			PossessionPercent: 'Possession - percent (%)',
			PossessionMinutes: 'Possession - minutes',
			PositionalAttacks: 'Positional attacks',
			PositionalAttacksWithShots: 'Positional attacks with shots',
			CounterAttacks: 'Counter attacks',
			FreekicksWithShots: 'Free kicks with shot',
			CornersWithShot: 'Corners with shot',
			CenterAttacks: 'Center attacks',
			RightFlankAttacks: 'Right flank attacks',
			LeftFlankAttacks: 'Left flank attacks',
			Tackles: 'Tackles',
			PPDA: "Passes allowed for opponent's team before defensive action",
			DefensiveDuelsSuccessful: 'Defensive successful duels',
			OffensiveDuelsSuccessful: 'Offensive successful duels',
			GroundDuels: 'Ground duels',
			GroundDuelsSuccessful: 'Ground successful duels',
			ChallengeIntensity: 'Challenge intensity',
			NoData: 'No data',
			LoadMore: 'Load more',
			NoCompareAccess: 'To compare yourself to other players, you must have a premium plan.',
			GoToPlans: 'Got to plans',
			Accurate: 'Accurate',
			Inaccurate: 'Inaccurate',
			Cooperation: 'Cooperation',
			DuelTime: 'Duel time',
			DuelOpponent: 'Duel opponent',
			DuelType: 'Duel type',
			ShotTime: 'Shot time',
			ShotType: 'Shot type',
			Goalkeeping: 'Goalkeeping',
			GoalKicks: 'Goal kicks',
			SuccessfulGoalKicks: 'Successful goal kicks',
			GoalKicksLong: 'Goal kicks long',
			GoalKicksShort: 'Goal kicks short',
			CleanSheets: 'Clean sheets',
			ConcededGoals: 'Conceded goals',
			GkShotsAgainst: 'Shots against',
			GkSaves: 'Saves',
			GkExits: 'Play outside the box',
			GkSuccessfulExits: 'Successful play outside the box',
		},
		validations: {
			required: "This field is required. ",
			email: "Please enter a valid email address. ",
			minLength: "Minimum length {minLength} characters. ",
			sameAs: "Passwords don't match. ",
			numeric: `Must be numeric. `,
		},
	},
	sk: {
		message: {
			myboard: 'Nástenka',
			stats: 'Štatistiky',
			match: 'Zápas',
			player: 'Hráč',
			Documents: 'Dokumenty',
			users: 'Používatelia',
			usersov: 'Používateľov',
			allUsers: 'Zoznam Používateľov',
			addNewUser: 'Pridať Používateľa',
			ufpNews: 'Správy UFP',
			Emails: 'Emaily',
			emailov: 'emailov',
			Footballnews: 'Futbalové správy',
			NewsRumors: 'Správy a Novinky',
			Settings: 'Nastavenia',
			Groups: 'Skupiny',
			Products: 'Produkty',
			Surveys: 'Dotazníky',
			Contact: 'Kontakt',
			ForgotPassword: 'Zabudnuté heslo',
			Login: 'Prihlásenie',
			LoginV: 'PRIHLÁSIŤ',
			Submit: 'Poslať',
			Password: 'Heslo',
			password: 'heslo',
			ForgotPasswordNotice: 'Vložte sem Váš prihlasovací email, na ktorý pošleme link pre reset hesla.',
			EmailRequired: 'Email je potrebný.',
			EmailNotValid: 'Email nie je platný.',
			UpdatePassword: 'Zmena hesla.',
			NewPassword: 'Nové heslo',
			ConfirmNewPassword: 'Potvrdenie nového hesla',
			PickAPassword: 'Výber hesla',
			Suggestions: 'Návrhy',
			Atleast: 'Aspoň',
			oneIt: 'jedno',
			lowercase: 'malé písmeno',
			uppercase: 'veľké písmeno',
			numeric: 'číslo',
			characters: 'písmen',
			Update: 'Aktualizovať',
			Nonewemails: 'Žiadne nové správy',
			Inbox: 'Schránka',
			Profile: 'Profil',
			Wallet: 'Peňaženka',
			Logout: 'Odhlásenie',
			MatchStats: 'Zápasové štatistiky',
			Season: 'Sezóna',
			Match: 'Zápas',
			SelectMatch: 'Vyberte Zápas',
			SelectSeason: 'Vyberte Sezónu',
			Playerstats: 'Štatistiky hráča',
			Matches: 'Zápasy',
			Minutesplayed: 'Odohrané minúty',
			Goals: 'Góly',
			Goal: 'Gól',
			Yellowcards: 'Žlté karty',
			Redcards: 'Červené karty',
			LINEUPS: 'ZOSTAVY',
			Lineups: 'Zostavy',
			STATS: 'ŠTATISTIKY',
			Stats: 'Štatistiky',
			TEAM: 'TÍM',
			Substitutes: 'Náhradníci',
			BallPossession: 'Držanie lopty',
			PurePossessionTime: 'Čistý čas držania lopty',
			AvgPossessionTime: 'Priemerný čas držania lopty',
			Shotsontarget: 'Strely na bránu',
			Completedpasses: 'Prihrávky',
			TotalAttempts: 'Strely',
			Fouls: 'Fauly',
			Corners: 'Rohy',
			Offsides: 'Ofsajdy',
			Freekicks: 'Voľné kopy',
			FreeKicksOnTarget: 'Voľné kopy na bránu',
			DirectFreeKicks: 'Priame voľné kopy',
			DirectFreeKicksOnTarget: 'Priame voľné kopy na bránu',
			Successfulduels: 'Úspešné súboje',
			Totallooses: 'Straty',
			LossesHigh: 'Straty v útočnej zóne',
			LossesMedium: 'Straty v strednej zóne',
			LossesLow: 'Straty v obranne zóne',
			OwnHalfLooses: 'Straty na vlastnej polovici',
			DangerousOwnHalfLooses: 'Nebezpečné straty na vlastnej polovici',
			Successfulpasses: 'Úspešné prihrávky',
			Shots: 'Strely',
			Shot: 'Strela',
			Duels: 'Súboje',
			Passes: 'Prihrávky',
			AerialDuels: 'Vzdušné súboje',
			AerialDuelsSuccessful: 'Úspešné vzdušné súboje',
			FieldAerialDuels: 'Vzdušné súboje v poli',
			DefensiveDuels: 'Defenzívne súboje',
			OffensiveDuels: 'Ofenzívne súboje',
			PressingDuels: 'Vytvorenia tlaku na protihráča',
			BackPasses: 'Prihrávky dozadu',
			BackPassesSuccessful: 'Úspešné prihrávky dozadu',
			ForwardPasses: 'Prihrávky dopredu',
			ForwardPassesSuccessful: 'Úspešné prihrávky dopredu',
			VerticalPasses: 'Vertikálne prihrávky',
			VerticalPassesSuccessful: 'Úspešné vertikálne prihrávky',
			ShotAssists: 'Assistencie k strele',
			SecondAssists: 'Druhé asistencie',
			BlockedShots: 'Zblokované strely',
			BlockedShot: 'Zblokovaná strela',
			Crosses: 'Centrované lopty',
			CrossesSuccessful: 'Úspešné centrované lopty',
			CrossesBlocked: 'Zblokované centrované lopty',
			CrossesLow: 'Prízemné centrované lopty',
			CrossesHigh: 'Vysoké centrované lopty',
			CrossesFromRightFlank: 'Centrované lopty z pravého krídla',
			CrossesFromRightFlankSuccessful: 'Úspešné centrované lopty z pravého krídla',
			CrossesFromLeftFlank: 'Centrované lopty z ľavého krídla',
			CrossesFromLeftFlankSuccessful: 'Úspešné centrované lopty z ľavého krídla',
			FoulsSuffered: 'Inkasované fauly',
			Dribbles: 'Driblingy',
			ReceivedPasses: 'Prijaté prihrávky',
			Losses: 'Straty',
			AttackingActions: 'Útočné akcie',
			DefensiveActions: 'Obranné akcie',
			KeywordSearch: 'Vyhľadať',
			ClearFilters: 'Vyčistiť filter',
			Name: 'Meno',
			Surname: 'Priezvisko',
			Select: 'Vyberte',
			Club: 'Klub',
			Fee: 'Členský poplatok',
			State: 'Stav',
			Activity: 'Aktivita',
			Showing: 'Zobrazených',
			to: 'až',
			To: 'Komu',
			of: 'z',
			SelectanAction: 'Vyberte akciu',
			SendEmail: 'Poslať email',
			AssignGroup: 'Priradiť skupinu',
			DetachGroup: 'Odobrať skupinu',
			EmailEditor: 'Editor emailov',
			SelectGroup: 'Vyberte skupinu',
			Choosed: 'Vybraní',
			Choose: 'Vyberte',
			PaymentMethod: 'platobnú metódu',
			PaymentMethodN: 'Platobná metóda',
			CreditDebitCard: 'Kreditná/Debetná karta',
			Continue: 'Pokračovať',
			Noemailsfound: 'Nenašli sa žiadne emaily.',
			Address: 'Adresa',
			Subject: 'Subjekt',
			Date: 'Dátum',
			DeleteEmails: 'Zmazať emaily',
			Nouserschosen: 'Žiadni vybratí užívatelia',
			Noemailschosen: 'Žiadne vybraté emaily.',
			Contactus: 'Kontaktujte nás',
			Insertmessage: 'Vložte správu',
			SelectRecipient: 'Vyberte príjemcu',
			UserData: 'Údaje o používateľovi',
			Code: 'Predvoľba',
			Phonenumber: 'Tel. číslo',
			Change: 'Zmeniť',
			Olde: 'Staré',
			Newe: 'Nové',
			Confirm: 'Potvrdite',
			Confirmation: 'Potvrdenie',
			Language: 'Jazyk',
			Yearly: 'Ročný',
			fee: 'poplatok',
			Membership: 'Členstvo',
			MemberFrom: 'Člen od',
			member: 'člen',
			Active: 'Aktívny',
			Inactive: 'Neaktívny',
			Paid: 'Uhradené',
			Unpaid: 'Neuhradené',
			Notregistered: 'Nie ste registrovaní',
			Create: 'VYTVORIŤ',
			Account: 'ÚČET',
			Register: 'Registrácia',
			RegisterV: 'REGISTROVAŤ',
			ConfirmPassword: 'Potvrdiť heslo',
			Youraccountisregisteredundername: 'Váš účet je zaregistrovaný pod menom:',
			andemail: 'a poslali sme potvrdzovací link na Váš email:',
			Alreadyaccount: 'Máte už účet',
			GlobalNews: 'Správy zo sveta',
			SelectaRole: 'Vyberte rolu',
			Generate: 'Generovať',
			Inordertoviewyourstatistics: 'Pre zobrazenie štatistík je potrebné vybrať zápas.',
			PERSONAL: 'OSOBNÉ',
			OnTarget: 'Na bránu',
			OffTarget: 'Mimo brány',
			Successful: 'Úspešné',
			Failed: 'Neúspešné',
			Other: 'Ďalšie',
			ThisSeason: 'Aktuálna sezóna',
			WeProtectIntro: 'Chránime Vaše futbalové záujmy.',
			WelcomeIntro: 'Vitajte na stránke oficiálnej aplikácie Únie Futbalových profesionálov Slovenska',
			Options: 'Možnosti',
			WithoutClub: 'Bez klubu',
			OtherClub: 'Iný klub',
			Myclubis: 'Môj klub',
			NameOfClub: 'Názov klubu',
			AgreeToTerms: 'Vytvorením účtu súhlasíte so',
			TermsOfUse: 'Zásadami používania',
			TermsOfUseN: 'Zásady používania',
			and: 'a',
			PrivacyPolicy: 'Zásadami ochrany osobných údajov',
			PrivacyPolicyN: 'Zásady ochrany osobných údajov',
			Templates: 'Šablóny',
			AddTo: 'Pripojiť na',
			Add: 'Pridať',
			Start: 'Začiatok',
			End: 'Koniec',
			template: 'šablónu',
			Title: 'Názov',
			Save: 'Uložiť',
			ReviewAll: 'Prezerajte všetky vaše individuálne štatistiky.',
			ReviewAlldesc: 'Prezrite si všetky vaše osobné štatistiky z wyscoutu a preverte vašu výkonnosť v zápasoch a sezónach.',
			Allthenews: 'Všetky správy z UFP v jednej aplikácii.',
			Allthenewsdesc: 'Sledujte všetky aktivity UFP v jednoduchej a pohodlnej aplikácii.',
			FastConnection: 'Rýchle spojenie priamo s UFP.',
			FastConnectionDesc: 'Spojte sa s UFP priamo v aplikácii a riešme spolu vaše potreby a problémy kedykoľvek sa vyskytnú.',
			SimplePayment: 'Jednoduchá platba za členstvo a prehľad platieb.',
			SimplePaymentDesc: 'Vykonajte platbu jednoduch použitím platobnej karty or Google Pay. Staňte sa jednoducho UFP členom.',
			SurveysInvolved: 'Zapojte sa do hlasovania v rámci UFP.',
			SurveysInvolvedDesc: 'Ako člen UFP máte možnosť ovplyvňovať výsledky volieb a dotazníkov zriadených UFP.',
			Skip: 'Preskočiť',
			SettingUpNotif: 'Nastavenie upozornení',
			SettingUpNotifDesc: 'Upozornenia je možné nastaviť kedykoľvek neskôr v nastaveniach aplikácie.',
			TurnOnNotif: 'ZAPNÚŤ UPOZORNENIA',
			NotNow: 'NESKÔR',
			MembershipDesc: 'Predplatením získate prístup k funkciám aplikácie vrátane osobných, tímových štatistík, právnym službám od právnikov UFP, výhodam od prtnerov UFP a ešte oveľa viac! (Konkrétne funkcie sú naviazane na balíček, ktorý si vyberiete)',
			Help: 'Pomoc',
			Board: 'Predsedníctvo',
			AddGroup: 'Pridať skupinu',
			AddEmails: 'Pridať emaily',
			Order: 'Poradie',
			Emails: 'Emaily',
			Members: 'Členovia',
			AddMembers: 'Pridať člena',
			Position: 'Pozícia',
			Description: 'Popis',
			Image: 'obrázok',
			GroupS: 'skupinu',
			Addp: 'Pridajte',
			Question: 'Otázka',
			Answer: 'Odpoveď',
			SendAnonymously: 'Poslať správu anonymne',
			AnonymousNotice: '*Pri anonymnom odosielaní emailu nebudeme prijímať o Vás žiadne informácie. Vezmite do úvahy, že nie je možné Vám odpovedať keďže nebudeme vedieť od koho sme správu prijali.',
			Payments: 'Platby',
			Payment: 'Platba',
			ProfileNotice: 'Zmena Vašich osobných informácií',
			PaymentsNotice: 'Zoznam Vašich platieb',
			LogoutNotice: 'Odhlásenie z aplikácie',
			Notifications: 'Upozornenia',
			NotificationsNotice: 'Upozornenia o dôležitých udalostiach',
			LanguageNotice: 'Zmena jazyka aplikácia',
			English: 'Angličtina',
			Slovak: 'Slovenčina',
			DateOfPayment: 'Dátum platby',
			Subscription: 'Predplatné',
			DateOfStart: 'Dátum vytvorenia predplatného',
			NextBillingDate: 'Dátum nasledujúcej platby',
			Cancel: 'Zrušiť',
			General: 'Hlavné',
			News: 'Správy',
			posts: 'články',
			No: 'Žiadne',
			More: 'Viac',
			Share: 'Zdieľať',
			MissedNews: 'Ďalšie správy...',
			Player: 'Hráč',
			PLAYER: 'HRÁČ',
			PersonalTeam: 'Osobné a tímové',
			MembershipFee: 'Členský poplatok',
			PlayerProfile: 'Hráčsky profil',
			Events: 'Udalosti',
			Media: 'Média',
			Podcasts: 'Podcasty',
			Agency: 'Agentúra',
			CategoryU: 'Kategóriu',
			Men: 'Muži',
			Women: 'Ženy',
			Gender: 'Pohlavie',
			Goalkeeper: 'Bránkar',
			Defenders: 'Obrancovia',
			Defender: 'Obránca',
			Midfielders: 'Stredopoliari',
			Midfielder: 'Stredopoliar',
			Strikers: 'Útočníci',
			Striker: 'Útočník',
			UploadImage: 'Nahrať titulný obrázok',
			PaymentPeriod: 'Platobný cyklus',
			Monthly: 'Mesačný',
			month: 'mesiac',
			year: 'rok',
			Yearly: 'Ročný',
			YearlyPaymentNotice: 'Ročná platba pokrývajúca kalendárny rok (sezónu) od 1.7 do 30.6. nasledujúceho roka.',
			yourplan: 'váš plán',
			Basic: 'Základný',
			Premium: 'Prémiový',
			PAY: 'ZAPLATIŤ',
			Pay: 'Zaplatiť',
			Includes: 'Obsahuje',
			MatchReports: 'Reporty zo zápasov',
			Personal: 'Osobné',
			MatchVideos: 'Videá zápasov',
			ComparisonWithOthers: 'Porovnanie s inými hráčmi',
			StatsOfOthers: 'Štatistiky a videá ostatných hráčov',
			RequireAction: 'Počkajte na automatické bezpečnostné presmerovanie.',
			PROCEEDTOPAYMENT: 'VYKONAŤ PLATBU',
			NotPaidNotice: 'Váš členský polatok nie je uhradený.',
			NotPaidNotice2: 'Na získanie prístupu k službám je potrebné zaplatiť členský poplatok.',
			FeeFinishDate: 'Koniec predplatného',
			Country: 'Krajina',
			Age: 'Vek',
			Number: 'Číslo',
			YourLastGames: 'Vaše posledné zápasy',
			SeeMore: 'Ukázať viac',
			YourMatchStats: 'Vaše zápasové štatistiky',
			YourSeasonStats: 'Vaše sezónne štatistiky',
			KEYSTATS: 'KĽÚČOVÉ',
			DISTRIBUTION: 'ROZDÁVANIE LÔPT',
			ATTACKING: 'ÚTOČNÉ',
			DEFENDING: 'OBRANNÉ',
			DUELS: 'SÚBOJE',
			Duel: 'Súboj',
			DISCIPLINARY: 'DISCIPLINÁRNE',
			PASSES: 'PRIHRÁVKY',
			MatchEvents: 'Zápasové situácie',
			Pass: 'Prihrávka',
			PassTime: 'Čas prihrávky',
			PassAccuracy: 'Presnosť prihrávky',
			PassLength: 'Dĺžka prihrávky',
			PassType: 'Typ prihrávky',
			PassRecipient: 'Príjemca prihrávky',
			PlayerComparison: 'Porovnanie hráčov',
			SearchPlayer: 'Vyhľadať hráča',
			Coach: 'Tréner',
			Attack: 'Útok',
			Defence: 'Obrana',
			Transitions: 'Prechody',
			Assists: 'Asistencie',
			SmartPasses: 'Dôvtipné prihrávky',
			Successful: 'Úspešné',
			Unsuccessful: 'Neúspešné',
			PassesToFinalThird: 'Prihrávky do útočnej zóny',
			PassesToFinalThirdSuccessful: 'Úspešné prihrávky do útočnej zóny',
			ThroughPasses: 'Prienikové prihrávky',
			ThroughPassesSuccessful: 'Úspešné prienikové prihrávky',
			KeyPasses: 'Kľúčové prihrávky',
			KeyPassesSuccessful: 'Úspešné kľúčové prihrávky',
			LongPasses: 'Dlhé prihrávky',
			LongPassesSuccessful: 'Úspešné dlhé prihrávky',
			ProgressivePasses: 'Progresívne prihrávky',
			ProgressivePassesSuccessful: 'Úspešné progresívne prihrávky',
			LateralPasses: 'Postranné prihrávky',
			LateralPassesSuccessful: 'Úspešné postranné prihrávky',
			TouchInBox: 'Dotyky v pokutovom území',
			ProgressiveRun: 'Progresívny beh',
			HeadShots: 'Strely hlavou',
			Penalties: 'Pokutové kopy',
			ThirdAssists: 'Tretie asistencie',
			ShotOnTargetAssists: 'Asistencie ku strele na bránu',
			MissedBalls: 'Stratené lopty',
			LinkupPlays: 'Akcie chrbtom k bráne',
			Accelerations: 'Akcelerácie',
			Interceptions: 'Zachytenia lopty',
			Recoveries: 'Získania lopty',
			RecoveriesHigh: 'Získania lopty v útočnej zóne',
			RecoveriesMedium: 'Získania lopty v strednej zóne',
			RecoveriesLow: 'Získania lopty v obrannej zóne',
			OpponentHalfRecoveries: 'Získania lopty na polovici súpera',
			DangerousOpponentHalfRecoveries: 'Nebezpečné získania lopty na polovici súpera',
			SlidingTackles: 'Odobratie lopty sklzom',
			Clearances: 'Odkop lopty bez tlaku súpera',
			LooseBallDuels: 'Súboje o neutrálnu lopty',
			LooseBallDuelsSuccessful: 'Úspešné súboje o neutrálnu lopty',
			DirectRedCards: 'Priame červené karty',
			UpgradeMembership: 'Aktualizovať členstvo na',
			Surcharge: 'Doplatok',
			UpgradeProduct: 'Produkt pre upgrade',
			from: 'z',
			to: 'na',
			response: 'odpoveď',
			All: 'Všetky',
			English: 'Angličtina',
			Slovak: 'Slovenčina',
			ForgotYour: 'Zabudli ste',
			EnterEmail: 'Vložte vašu emailovú adresu',
			SelectFrom: 'Vybrať od čísla',
			SelectTo: 'do',
			ShotsOutsideBox: 'Strely mimo pokutové územie',
			ShotsOutsideBoxOnTarget: 'Presné strely mimo pokutové územie',
			ShotsOnPost: 'Strely do konštrukcie brány',
			ShotsWide: 'Strely mimo brány',
			ShotsFromBox: 'Strely z pokutového územia',
			ShotsFromDangerZone: 'Strely z nebezpečnej zóny',
			PlayerDetails: 'Detaily hráča',
			PassesToPenalty: 'Prihávky do pokutového územia',
			PassesToPenaltySuccessful: 'Úspešné prihávky do pokutového územia',
			ThrowIns: 'Vhadzovania',
			RightThrowIns: 'Vhadzovania z pravej strany',
			LeftThrowIns: 'Vhadzovania z ľavej strany',
			ReachingOpponentHalf: 'Vniknutia na polovicu súpera',
			ReachingOpponentBox: 'Vniknutia do pokutového územia súpera',
			PossessionPercent: 'Držanie lopty v percentách (%)',
			PossessionMinutes: 'Držanie lopty v minutách',
			PositionalAttacks: 'Organizovaný (pozičný) útok',
			PositionalAttacksWithShots: 'Organizovaný (pozičný) útok so zakončením',
			CounterAttacks: 'Protiútoky',
			FreekicksWithShots: 'Voľný kop so zakončením',
			CornersWithShot: 'Rohy so zakončením',
			CenterAttacks: 'Útoky vedené stredom',
			RightFlankAttacks: 'Útoky vedené po pravom krídle',
			LeftFlankAttacks: 'Útoky vedené po ľavom krídle',
			Tackles: 'Odobratia lopty',
			PPDA: 'Počet prihravok dovolených súperovi pred prerušením akcie',
			DefensiveDuelsSuccessful: 'Úspešné defenzívne súboje',
			OffensiveDuelsSuccessful: 'Úspešné ofenzívne súboje',
			GroundDuels: 'Pozemné súboje',
			GroundDuelsSuccessful: 'Úspešné pozemné súboje',
			ChallengeIntensity: 'Intenzita súbojov',
			NoData: 'Žiadne údaje',
			LoadMore: 'Načítať viac',
			NoCompareAccess: 'Pre porovnanie s inými hráčmi, je potrebné mať predplatenú prémiovú verziu.',
			GoToPlans: 'Ísť na predplatné',
			Accurate: 'Presný',
			Inaccurate: 'Nepresný',
			Cooperation: 'Spolupráca',
			DuelTime: 'Čas súboja',
			DuelOpponent: 'Oponent',
			DuelType: 'Typ súboja',
			ShotTime: 'Čas strely',
			ShotType: 'Typ strely',
			Goalkeeping: 'Brankár',
			GoalKicks: 'Odkopy od brány',
			SuccessfulGoalKicks: 'Úspešné odkopy od brány',
			GoalKicksLong: 'Dlhé odkopy od brány',
			GoalKicksShort: 'Krátke odkopy od brány',
			CleanSheets: 'Zápasy bez inkasovaných gólov',
			ConcededGoals: 'Inkasované goly',
			GkShotsAgainst: 'Vyslané strely proti',
			GkSaves: 'Chytené strely',
			GkExits: 'Aktívna hra mimo pokutového územia',
			GkSuccessfulExits: 'Úspešná aktívna hra mimo pokutového územia',
		},
		validations: {
			required: "Toto pole je potrebné vyplniť. ",
			email: "Vložte platný email. ",
			minLength: `Minimálna dĺžka{minLength} znakov. `,
			sameAs: `Heslá sa nezhodujú. `,
			numeric: "Musí byť číslo. ",
		},
	}
}
/* export function getMessages(minLength) {
	return {
		en: {
		message: {
			myboard: 'Board',
			stats: 'Stats',
			match: 'Match',
			player: 'Player',
			Documents: 'Documents',
			users: 'Users',
			usersov: 'Users',
			allUsers: 'All Users',
			addNewUser: 'Add New User',
			ufpNews: 'UFP News',
			Emails: 'Emails',
			emailov: 'Emails',
			Footballnews: 'Football News',
			NewsRumors: 'News & Rumors',
			Settings: 'Settings',
			Groups: 'Groups',
			Products: 'Products',
			Surveys: 'Surveys',
			Contact: 'Contact',
			ForgotPassword: 'Forgot Password',
			Login: 'Log In',
			LoginV: 'LOG IN',
			Submit: 'Submit',
			Password: 'Password',
			password: 'password',
			ForgotPasswordNotice: 'Input your email and we will send you reset password link.',
			EmailRequired: 'Email is Required.',
			EmailNotValid: 'Email is not valid.',
			UpdatePassword: 'Update Password',
			NewPassword: 'New Password',
			ConfirmNewPassword: 'Confirm New Password',
			PickAPassword: 'Pick a password',
			Suggestions: 'Suggestions',
			Atleast: 'At least',
			oneIt: 'one',
			lowercase: 'lowercase',
			uppercase: 'uppercase',
			numeric: 'numeric',
			characters: 'characters',
			Update: 'Update',
			Nonewemails: 'No new emails',
			Inbox: 'Inbox',
			Profile: 'Profile',
			Wallet: 'Wallet',
			Logout: 'Logout',
			MatchStats: 'Match Stats',
			Season: 'Season',
			Match: 'Match',
			SelectMatch: 'Select Match',
			SelectSeason: 'Select Season',
			Playerstats: 'Player stats',
			Matches: 'Matches',
			Minutesplayed: 'Minutes played',
			Goals: 'Goals',
			Yellowcards: 'Yellow cards',
			Redcards: 'Red cards',
			LINEUPS: 'LINEUPS',
			STATS: 'STATS',
			TEAM: 'TEAM',
			Substitutions: 'Substitutions',
			BallPossession: 'Ball Possession',
			Shotsontarget: 'Shots On Target',
			Completedpasses: 'Completed passes',
			TotalAttempts: 'Total Attempts',
			Fouls: 'Fouls',
			Corners: 'Corners',
			Offsides: 'Offsides',
			Freekicks: 'Freekicks',
			Successfulduels: 'Successful Duels',
			Totallooses: 'Total Looses',
			Successfulpasses: 'Successful Passes',
			Shots: 'Shots',
			Duels: 'Duels',
			Passes: 'Passes',
			AerialDuels: 'Aerial Duels',
			DefensiveDuels: 'Defensive Duels',
			OffensiveDuels: 'Offensive Duels',
			BackPasses: 'Back Passes',
			ForwardPasses: 'Forward Passes',
			VerticalPasses: 'Vertical Passes',
			ShotAssists: 'Shot Assists',
			BlockedShots: 'Blocked Shots',
			Crosses: 'Crosses',
			FoulsSuffered: 'Fouls Suffered',
			Dribbles: 'Dribbles',
			ReceivedPasses: 'Received Passes',
			Losses: 'Losses',
			AttackingActions: 'Attacking Actions',
			DefensiveActions: 'Defensive Actions',
			KeywordSearch: 'Keyword Search',
			ClearFilters: 'Clear Filters',
			Name: 'Name',
			Surname: 'Surname',
			Club: 'Club',
			Fee: 'Fee',
			State: 'State',
			Activity: 'Activity',
			Showing: 'Showing',
			to: 'to',
			To: 'To',
			of: 'of',
			SelectanAction: 'Select an Action',
			SendEmail: 'Send Email',
			AssignGroup: 'Assign Group',
			DetachGroup: 'Detach Group',
			EmailEditor: 'Email Editor',
			SelectGroup: 'Select Group',
			Choosed: 'Choosed',
			Choose: 'Choose',
			PaymentMethod: 'Payment Method',
			CreditDebitCard: 'Credit/Debit card',
			Continue: 'Continue',
			Noemailsfound: 'No emails found.',
			Address: 'Address',
			Subject: 'Subject',
			Date: 'Date',
			DeleteEmails: 'Delete Emails',
			Nouserschosen: 'No users chosen.',
			Noemailschosen: 'No emails chosen.',
			Contactus: 'Contact us',
			Insertmessage: 'Insert message',
			SelectRecipient: 'Select Recipient',
			UserData: 'User Data',
			Code: 'Code',
			Phonenumber: 'Phone number',
			Change: 'Change',
			Olde: 'Old',
			Newe: 'New',
			Confirm: 'Confirm',
			Confirmation: 'Confirmation',
			Language: 'Language',
			Yearly: 'Yearly',
			fee: 'fee',
			Membership: 'Membership',
			MemberFrom: 'Member From',
			member: 'member',
			Active: 'Active',
			Inactive: 'Inactive',
			Active: 'active',
			Paid: 'Paid',
			Unpaid: 'Unpaid',
			Notregistered: 'Not registered',
			Create: 'CREATE',
			Account: 'ACCOUNT',
			Register: 'Register',
			RegisterV: 'REGISTER',
			ConfirmPassword: 'Confirm Password',
			Youraccountisregisteredundername: 'Your account is registered under name:',
			andemail: 'and we have sent verify link on your email:',
			Alreadyaccount: 'Already have account',
			GlobalNews: 'Global News',
			SelectaRole: 'Select a Role',
			Generate: 'Generate',
			Inordertoviewyourstatistics: 'In order to view your statistics, you need to select the desired match first.',
			PERSONAL: 'PERSONAL',
			OnTarget: 'On Target',
			OffTarget: 'Off Target',
			Successful: 'Successful',
			Failed: 'Failed',
			Other: 'Other',
			ThisSeason: 'This season',
			WeProtectIntro: 'We protect your football interests',
			WelcomeIntro: 'Welcome to the official app of the Union of Football Professionals in Slovakia.',
		},
		validations: {
			required: "This field is required.",
			email: "Please enter a valid email address.",
			minLength: `Minimum length is ${minLength} characters`,
			sameAs: "Passwords don't match"
		},
		},
		sk: {
		message: {
			myboard: 'Nástenka',
			stats: 'Štatistiky',
			match: 'Zápas',
			player: 'Hráč',
			Documents: 'Dokumenty',
			users: 'Používatelia',
			usersov: 'Používateľov',
			allUsers: 'Zoznam Používateľov',
			addNewUser: 'Pridať Používateľa',
			ufpNews: 'Správy UFP',
			Emails: 'Emaily',
			emailov: 'emailov',
			Footballnews: 'Futbalové správy',
			NewsRumors: 'Správy a Novinky',
			Settings: 'Nastavenia',
			Groups: 'Skupiny',
			Products: 'Produkty',
			Surveys: 'Dotazníky',
			Contact: 'Kontakt',
			ForgotPassword: 'Zabudnuté heslo',
			Login: 'Prihlásenie',
			LoginV: 'PRIHLÁSIŤ',
			Submit: 'Poslať',
			Password: 'Heslo',
			password: 'heslo',
			ForgotPasswordNotice: 'Vložte sem Váš prihlasovací email, na ktorý pošleme link pre reset hesla.',
			EmailRequired: 'Email je potrebný.',
			EmailNotValid: 'Email nie je platný.',
			UpdatePassword: 'Zmena hesla.',
			NewPassword: 'Nové heslo',
			ConfirmNewPassword: 'Potvrdenie nového hesla',
			PickAPassword: 'Výber hesla',
			Suggestions: 'Návrhy',
			Atleast: 'Aspoň',
			oneIt: 'jedno',
			lowercase: 'malé písmeno',
			uppercase: 'veľké písmeno',
			numeric: 'číslo',
			characters: 'písmen',
			Update: 'Aktualizovať',
			Nonewemails: 'Žiadne nové správy',
			Inbox: 'Schránka',
			Profile: 'Profil',
			Wallet: 'Peňaženka',
			Logout: 'Odhlásenie',
			MatchStats: 'Zápasové štatistiky',
			Season: 'Sezóna',
			Match: 'Zápas',
			SelectMatch: 'Vyberte Zápas',
			SelectSeason: 'Vyberte Sezónu',
			Playerstats: 'Štatistiky hráča',
			Matches: 'Zápasy',
			Minutesplayed: 'Odohrané minúty',
			Goals: 'Góly',
			Yellowcards: 'Žlté karty',
			Redcards: 'Červené karty',
			LINEUPS: 'ZOSTAVY',
			STATS: 'ŠTATISTIKY',
			TEAM: 'TÍM',
			Substitutions: 'Náhradníci',
			BallPossession: 'Držanie lopty',
			Shotsontarget: 'Strely na bránu',
			Completedpasses: 'Prihrávky',
			TotalAttempts: 'Strely',
			Fouls: 'Fauly',
			Corners: 'Rohy',
			Offsides: 'Ofsajdy',
			Freekicks: 'Voľné kopy',
			Successfulduels: 'Úspešné súboje',
			Totallooses: 'Straty',
			Successfulpasses: 'Úspešné prihrávy',
			Shots: 'Strely',
			Duels: 'Súboje',
			Passes: 'Prihrávky',
			AerialDuels: 'Vzdušné súboje',
			DefensiveDuels: 'Defenzívne súboje',
			OffensiveDuels: 'Ofenzívne súboje',
			BackPasses: 'Prihrávky dozadu',
			ForwardPasses: 'Prihrávky dopredu',
			VerticalPasses: 'Vertikálne prihrávky',
			ShotAssists: 'Assistencie k strele',
			BlockedShots: 'Zblokované strely',
			Crosses: 'Centrované lopty',
			FoulsSuffered: 'Inkasované fauly',
			Dribbles: 'Driblingy',
			ReceivedPasses: 'Prijaté prihrávky',
			Losses: 'Straty',
			AttackingActions: 'Útočné akcie',
			DefensiveActions: 'Obranné akcie',
			KeywordSearch: 'Vyhľadať',
			ClearFilters: 'Vyčistiť filter',
			Name: 'Meno',
			Surname: 'Priezvisko',
			Club: 'Klub',
			Fee: 'Členské',
			State: 'Stav',
			Activity: 'Aktivita',
			Showing: 'Zobrazených',
			to: 'až',
			To: 'Komu',
			of: 'z',
			SelectanAction: 'Vyberte akciu',
			SendEmail: 'Poslať email',
			AssignGroup: 'Priradiť skupinu',
			DetachGroup: 'Odobrať skupinu',
			EmailEditor: 'Editor emailov',
			SelectGroup: 'Vyberte skupinu',
			Choosed: 'Vybraní',
			Choose: 'Vyberte',
			PaymentMethod: 'platobnú metódu',
			CreditDebitCard: 'Kreditná/Debetná karta',
			Continue: 'Pokračovať',
			Noemailsfound: 'Nenašli sa žiadne emaily.',
			Address: 'Adresa',
			Subject: 'Subjekt',
			Date: 'Dátum',
			DeleteEmails: 'Zmazať emaily',
			Nouserschosen: 'Žiadni vybratí užívatelia',
			Noemailschosen: 'Žiadne vybraté emaily.',
			Contactus: 'Kontaktujte nás',
			Insertmessage: 'Vložte správu',
			SelectRecipient: 'Vyberte príjemcu',
			UserData: 'Udaje o používateľovi',
			Code: 'Predvoľba',
			Phonenumber: 'Tel. číslo',
			Change: 'Zmeniť',
			Olde: 'Staré',
			Newe: 'Nové',
			Confirm: 'Potvrdite',
			Confirmation: 'Potvrdenie',
			Language: 'Jazyk',
			Yearly: 'Ročný',
			fee: 'poplatok',
			Membership: 'Členstvo',
			MemberFrom: 'Člen od',
			member: 'člen',
			Active: 'Aktívny',
			Inactive: 'Neaktívny',
			Paid: 'Uhradené',
			Unpaid: 'Neuhradené',
			Notregistered: 'Nie ste registrovaní',
			Create: 'VYTVORIŤ',
			Account: 'ÚČET',
			Register: 'Registrácia',
			RegisterV: 'REGISTROVAŤ',
			ConfirmPassword: 'Potvrdiť heslo',
			Youraccountisregisteredundername: 'Váš účet je zaregistrovaný pod menom:',
			andemail: 'a poslali sme potvrdzovací link na Váš email:',
			Alreadyaccount: 'Máte už účet',
			GlobalNews: 'Správy zo sveta',
			SelectaRole: 'Vyberte rolu',
			Generate: 'Generovať',
			Inordertoviewyourstatistics: 'Pre zobrazenie štatistík je potrebné vybrať zápas.',
			PERSONAL: 'OSOBNÉ',
			OnTarget: 'Na bránu',
			OffTarget: 'Mimo brány',
			Successful: 'Úspešné',
			Failed: 'Neúspešné',
			Other: 'Ďalšie',
			ThisSeason: 'Aktuálna sezóna',
			WeProtectIntro: 'Chránime Vaše futbalové záujmy.',
			WelcomeIntro: 'Vitajte na stránke oficiálnej aplikácie Únie Futbalových profesionálov Slovenska',
		},
		validations: {
			required: "Toto pole je nevyhnutné.",
			email: "Vložte platný email.",
			minLength: `Minimálna dĺžka je ${minLength} znakov`,
			sameAs: `Heslá sa nezhodujú`,
		},
		}
	}
  } */