export const messages = {
		en: {
		message: {
			myboard: 'Board',
			stats: 'Stats',
			match: 'Match',
			player: 'Player',
			Documents: 'Documents',
			users: 'Users',
			usersov: 'Users',
			allUsers: 'All Users',
			addNewUser: 'Add New User',
			ufpNews: 'UFP News',
			Emails: 'Emails',
			emailov: 'Emails',
			Footballnews: 'Football News',
			NewsRumors: 'News & Rumors',
			Settings: 'Settings',
			Groups: 'Groups',
			Products: 'Products',
			Surveys: 'Surveys',
			Contact: 'Contact',
			ForgotPassword: 'Forgot Password',
			Login: 'Log In',
			LoginV: 'LOG IN',
			Submit: 'Submit',
			Password: 'Password',
			password: 'password',
			ForgotPasswordNotice: 'Input your email and we will send you reset password link.',
			EmailRequired: 'Email is Required.',
			EmailNotValid: 'Email is not valid.',
			UpdatePassword: 'Update Password',
			NewPassword: 'New Password',
			ConfirmNewPassword: 'Confirm New Password',
			PickAPassword: 'Pick a password',
			Suggestions: 'Suggestions',
			Atleast: 'At least',
			oneIt: 'one',
			lowercase: 'lowercase',
			uppercase: 'uppercase',
			numeric: 'numeric',
			characters: 'characters',
			Update: 'Update',
			Nonewemails: 'No new emails',
			Inbox: 'Inbox',
			Profile: 'Profile',
			Wallet: 'Wallet',
			Logout: 'Logout',
			MatchStats: 'Match Stats',
			Season: 'Season',
			Match: 'Match',
			SelectMatch: 'Select Match',
			SelectSeason: 'Select Season',
			Playerstats: 'Player stats',
			Matches: 'Matches',
			Minutesplayed: 'Minutes played',
			Goals: 'Goals',
			Yellowcards: 'Yellow cards',
			Redcards: 'Red cards',
			LINEUPS: 'LINEUPS',
			STATS: 'STATS',
			TEAM: 'TEAM',
			Substitutions: 'Substitutions',
			BallPossession: 'Ball Possession',
			Shotsontarget: 'Shots On Target',
			Completedpasses: 'Completed passes',
			TotalAttempts: 'Total Attempts',
			Fouls: 'Fouls',
			Corners: 'Corners',
			Offsides: 'Offsides',
			Freekicks: 'Freekicks',
			Successfulduels: 'Successful Duels',
			Totallooses: 'Total Looses',
			Successfulpasses: 'Successful Passes',
			Shots: 'Shots',
			Duels: 'Duels',
			Passes: 'Passes',
			AerialDuels: 'Aerial Duels',
			DefensiveDuels: 'Defensive Duels',
			OffensiveDuels: 'Offensive Duels',
			BackPasses: 'Back Passes',
			ForwardPasses: 'Forward Passes',
			VerticalPasses: 'Vertical Passes',
			ShotAssists: 'Shot Assists',
			BlockedShots: 'Blocked Shots',
			Crosses: 'Crosses',
			FoulsSuffered: 'Fouls Suffered',
			Dribbles: 'Dribbles',
			ReceivedPasses: 'Received Passes',
			Losses: 'Losses',
			AttackingActions: 'Attacking Actions',
			DefensiveActions: 'Defensive Actions',
			KeywordSearch: 'Keyword Search',
			ClearFilters: 'Clear Filters',
			Name: 'Name',
			Surname: 'Surname',
			Select: 'Select',
			Club: 'Club',
			Fee: 'Fee',
			State: 'State',
			Activity: 'Activity',
			Showing: 'Showing',
			to: 'to',
			To: 'To',
			of: 'of',
			SelectanAction: 'Select an Action',
			SendEmail: 'Send Email',
			AssignGroup: 'Assign Group',
			DetachGroup: 'Detach Group',
			EmailEditor: 'Email Editor',
			SelectGroup: 'Select Group',
			Choosed: 'Choosed',
			Choose: 'Choose',
			PaymentMethod: 'Payment Method',
			CreditDebitCard: 'Credit/Debit card',
			Continue: 'Continue',
			Noemailsfound: 'No emails found.',
			Address: 'Address',
			Subject: 'Subject',
			Date: 'Date',
			DeleteEmails: 'Delete Emails',
			Nouserschosen: 'No users chosen.',
			Noemailschosen: 'No emails chosen.',
			Contactus: 'Contact us',
			Insertmessage: 'Insert message',
			SelectRecipient: 'Select Recipient',
			UserData: 'User Data',
			Code: 'Code',
			Phonenumber: 'Phone number',
			Change: 'Change',
			Olde: 'Old',
			Newe: 'New',
			Confirm: 'Confirm',
			Confirmation: 'Confirmation',
			Language: 'Language',
			Yearly: 'Yearly',
			fee: 'fee',
			Membership: 'Membership',
			MemberFrom: 'Member From',
			member: 'member',
			Active: 'Active',
			Inactive: 'Inactive',
			Active: 'active',
			Paid: 'Paid',
			Unpaid: 'Unpaid',
			Notregistered: 'Not registered',
			Create: 'CREATE',
			Account: 'ACCOUNT',
			Register: 'Register',
			RegisterV: 'REGISTER',
			ConfirmPassword: 'Confirm Password',
			Youraccountisregisteredundername: 'Your account is registered under name:',
			andemail: 'and we have sent verify link on your email:',
			Alreadyaccount: 'Already have account',
			GlobalNews: 'Global News',
			SelectaRole: 'Select a Role',
			Generate: 'Generate',
			Inordertoviewyourstatistics: 'In order to view your statistics, you need to select the desired match first.',
			PERSONAL: 'PERSONAL',
			OnTarget: 'On Target',
			OffTarget: 'Off Target',
			Successful: 'Successful',
			Failed: 'Failed',
			Other: 'Other',
			ThisSeason: 'This season',
			WeProtectIntro: 'We protect your football interests',
			WelcomeIntro: 'Welcome to the official app of the Union of Football Professionals in Slovakia.',
			Options: 'Options',
			WithoutClub: 'Without Club',
			OtherClub: 'Other Club',
			Myclubis: 'My club is',
			NameOfClub: 'Name of club',
			AgreeToTerms: 'By creating an account, you agree to our',
			TermsOfUse: 'Terms of Use',
			and: 'and',
			PrivacyPolicy: 'Privacy Policy',
			Templates: 'Templates',
			AddTo: 'Add to',
			Add: 'Add',
			Start: 'Start',
			End: 'End',
			template: 'template',
			Title: 'Title',
			Save: 'Save',
		},
		validations: {
			required: "This field is required. ",
			email: "Please enter a valid email address. ",
			minLength: "Minimum length {minLength} characters. ",
			sameAs: "Passwords don't match. ",
			numeric: `Must be numeric. `,
		},
		},
		sk: {
		message: {
			myboard: 'Nástenka',
			stats: 'Štatistiky',
			match: 'Zápas',
			player: 'Hráč',
			Documents: 'Dokumenty',
			users: 'Používatelia',
			usersov: 'Používateľov',
			allUsers: 'Zoznam Používateľov',
			addNewUser: 'Pridať Používateľa',
			ufpNews: 'Správy UFP',
			Emails: 'Emaily',
			emailov: 'emailov',
			Footballnews: 'Futbalové správy',
			NewsRumors: 'Správy a Novinky',
			Settings: 'Nastavenia',
			Groups: 'Skupiny',
			Products: 'Produkty',
			Surveys: 'Dotazníky',
			Contact: 'Kontakt',
			ForgotPassword: 'Zabudnuté heslo',
			Login: 'Prihlásenie',
			LoginV: 'PRIHLÁSIŤ',
			Submit: 'Poslať',
			Password: 'Heslo',
			password: 'heslo',
			ForgotPasswordNotice: 'Vložte sem Váš prihlasovací email, na ktorý pošleme link pre reset hesla.',
			EmailRequired: 'Email je potrebný.',
			EmailNotValid: 'Email nie je platný.',
			UpdatePassword: 'Zmena hesla.',
			NewPassword: 'Nové heslo',
			ConfirmNewPassword: 'Potvrdenie nového hesla',
			PickAPassword: 'Výber hesla',
			Suggestions: 'Návrhy',
			Atleast: 'Aspoň',
			oneIt: 'jedno',
			lowercase: 'malé písmeno',
			uppercase: 'veľké písmeno',
			numeric: 'číslo',
			characters: 'písmen',
			Update: 'Aktualizovať',
			Nonewemails: 'Žiadne nové správy',
			Inbox: 'Schránka',
			Profile: 'Profil',
			Wallet: 'Peňaženka',
			Logout: 'Odhlásenie',
			MatchStats: 'Zápasové štatistiky',
			Season: 'Sezóna',
			Match: 'Zápas',
			SelectMatch: 'Vyberte Zápas',
			SelectSeason: 'Vyberte Sezónu',
			Playerstats: 'Štatistiky hráča',
			Matches: 'Zápasy',
			Minutesplayed: 'Odohrané minúty',
			Goals: 'Góly',
			Yellowcards: 'Žlté karty',
			Redcards: 'Červené karty',
			LINEUPS: 'ZOSTAVY',
			STATS: 'ŠTATISTIKY',
			TEAM: 'TÍM',
			Substitutions: 'Náhradníci',
			BallPossession: 'Držanie lopty',
			Shotsontarget: 'Strely na bránu',
			Completedpasses: 'Prihrávky',
			TotalAttempts: 'Strely',
			Fouls: 'Fauly',
			Corners: 'Rohy',
			Offsides: 'Ofsajdy',
			Freekicks: 'Voľné kopy',
			Successfulduels: 'Úspešné súboje',
			Totallooses: 'Straty',
			Successfulpasses: 'Úspešné prihrávy',
			Shots: 'Strely',
			Duels: 'Súboje',
			Passes: 'Prihrávky',
			AerialDuels: 'Vzdušné súboje',
			DefensiveDuels: 'Defenzívne súboje',
			OffensiveDuels: 'Ofenzívne súboje',
			BackPasses: 'Prihrávky dozadu',
			ForwardPasses: 'Prihrávky dopredu',
			VerticalPasses: 'Vertikálne prihrávky',
			ShotAssists: 'Assistencie k strele',
			BlockedShots: 'Zblokované strely',
			Crosses: 'Centrované lopty',
			FoulsSuffered: 'Inkasované fauly',
			Dribbles: 'Driblingy',
			ReceivedPasses: 'Prijaté prihrávky',
			Losses: 'Straty',
			AttackingActions: 'Útočné akcie',
			DefensiveActions: 'Obranné akcie',
			KeywordSearch: 'Vyhľadať',
			ClearFilters: 'Vyčistiť filter',
			Name: 'Meno',
			Surname: 'Priezvisko',
			Select: 'Vyberte',
			Club: 'Klub',
			Fee: 'Členské',
			State: 'Stav',
			Activity: 'Aktivita',
			Showing: 'Zobrazených',
			to: 'až',
			To: 'Komu',
			of: 'z',
			SelectanAction: 'Vyberte akciu',
			SendEmail: 'Poslať email',
			AssignGroup: 'Priradiť skupinu',
			DetachGroup: 'Odobrať skupinu',
			EmailEditor: 'Editor emailov',
			SelectGroup: 'Vyberte skupinu',
			Choosed: 'Vybraní',
			Choose: 'Vyberte',
			PaymentMethod: 'platobnú metódu',
			CreditDebitCard: 'Kreditná/Debetná karta',
			Continue: 'Pokračovať',
			Noemailsfound: 'Nenašli sa žiadne emaily.',
			Address: 'Adresa',
			Subject: 'Subjekt',
			Date: 'Dátum',
			DeleteEmails: 'Zmazať emaily',
			Nouserschosen: 'Žiadni vybratí užívatelia',
			Noemailschosen: 'Žiadne vybraté emaily.',
			Contactus: 'Kontaktujte nás',
			Insertmessage: 'Vložte správu',
			SelectRecipient: 'Vyberte príjemcu',
			UserData: 'Udaje o používateľovi',
			Code: 'Predvoľba',
			Phonenumber: 'Tel. číslo',
			Change: 'Zmeniť',
			Olde: 'Staré',
			Newe: 'Nové',
			Confirm: 'Potvrdite',
			Confirmation: 'Potvrdenie',
			Language: 'Jazyk',
			Yearly: 'Ročný',
			fee: 'poplatok',
			Membership: 'Členstvo',
			MemberFrom: 'Člen od',
			member: 'člen',
			Active: 'Aktívny',
			Inactive: 'Neaktívny',
			Paid: 'Uhradené',
			Unpaid: 'Neuhradené',
			Notregistered: 'Nie ste registrovaní',
			Create: 'VYTVORIŤ',
			Account: 'ÚČET',
			Register: 'Registrácia',
			RegisterV: 'REGISTROVAŤ',
			ConfirmPassword: 'Potvrdiť heslo',
			Youraccountisregisteredundername: 'Váš účet je zaregistrovaný pod menom:',
			andemail: 'a poslali sme potvrdzovací link na Váš email:',
			Alreadyaccount: 'Máte už účet',
			GlobalNews: 'Správy zo sveta',
			SelectaRole: 'Vyberte rolu',
			Generate: 'Generovať',
			Inordertoviewyourstatistics: 'Pre zobrazenie štatistík je potrebné vybrať zápas.',
			PERSONAL: 'OSOBNÉ',
			OnTarget: 'Na bránu',
			OffTarget: 'Mimo brány',
			Successful: 'Úspešné',
			Failed: 'Neúspešné',
			Other: 'Ďalšie',
			ThisSeason: 'Aktuálna sezóna',
			WeProtectIntro: 'Chránime Vaše futbalové záujmy.',
			WelcomeIntro: 'Vitajte na stránke oficiálnej aplikácie Únie Futbalových profesionálov Slovenska',
			Options: 'Možnosti',
			WithoutClub: 'Bez klubu',
			OtherClub: 'Iný klub',
			Myclubis: 'Môj klub',
			NameOfClub: 'Názov klubu',
			AgreeToTerms: 'Vytvorením účtu súhlasíte so',
			TermsOfUse: 'Zásadami používania',
			and: 'a',
			PrivacyPolicy: 'Zásadami ochrany osobných údajov',
			Templates: 'Šablóny',
			AddTo: 'Pripojiť na',
			Add: 'Pridať',
			Start: 'Začiatok',
			End: 'Koniec',
			template: 'šablónu',
			Title: 'Názov',
			Save: 'Uložiť',
		},
		validations: {
			required: "Toto pole je nevyhnutné. ",
			email: "Vložte platný email. ",
			minLength: `Minimálna dĺžka {minLength} znakov. `,
			sameAs: `Heslá sa nezhodujú. `,
			numeric: "Musí byť číslo. ",
		},
	}
}
/* export function getMessages(minLength) {
	return {
		en: {
		message: {
			myboard: 'Board',
			stats: 'Stats',
			match: 'Match',
			player: 'Player',
			Documents: 'Documents',
			users: 'Users',
			usersov: 'Users',
			allUsers: 'All Users',
			addNewUser: 'Add New User',
			ufpNews: 'UFP News',
			Emails: 'Emails',
			emailov: 'Emails',
			Footballnews: 'Football News',
			NewsRumors: 'News & Rumors',
			Settings: 'Settings',
			Groups: 'Groups',
			Products: 'Products',
			Surveys: 'Surveys',
			Contact: 'Contact',
			ForgotPassword: 'Forgot Password',
			Login: 'Log In',
			LoginV: 'LOG IN',
			Submit: 'Submit',
			Password: 'Password',
			password: 'password',
			ForgotPasswordNotice: 'Input your email and we will send you reset password link.',
			EmailRequired: 'Email is Required.',
			EmailNotValid: 'Email is not valid.',
			UpdatePassword: 'Update Password',
			NewPassword: 'New Password',
			ConfirmNewPassword: 'Confirm New Password',
			PickAPassword: 'Pick a password',
			Suggestions: 'Suggestions',
			Atleast: 'At least',
			oneIt: 'one',
			lowercase: 'lowercase',
			uppercase: 'uppercase',
			numeric: 'numeric',
			characters: 'characters',
			Update: 'Update',
			Nonewemails: 'No new emails',
			Inbox: 'Inbox',
			Profile: 'Profile',
			Wallet: 'Wallet',
			Logout: 'Logout',
			MatchStats: 'Match Stats',
			Season: 'Season',
			Match: 'Match',
			SelectMatch: 'Select Match',
			SelectSeason: 'Select Season',
			Playerstats: 'Player stats',
			Matches: 'Matches',
			Minutesplayed: 'Minutes played',
			Goals: 'Goals',
			Yellowcards: 'Yellow cards',
			Redcards: 'Red cards',
			LINEUPS: 'LINEUPS',
			STATS: 'STATS',
			TEAM: 'TEAM',
			Substitutions: 'Substitutions',
			BallPossession: 'Ball Possession',
			Shotsontarget: 'Shots On Target',
			Completedpasses: 'Completed passes',
			TotalAttempts: 'Total Attempts',
			Fouls: 'Fouls',
			Corners: 'Corners',
			Offsides: 'Offsides',
			Freekicks: 'Freekicks',
			Successfulduels: 'Successful Duels',
			Totallooses: 'Total Looses',
			Successfulpasses: 'Successful Passes',
			Shots: 'Shots',
			Duels: 'Duels',
			Passes: 'Passes',
			AerialDuels: 'Aerial Duels',
			DefensiveDuels: 'Defensive Duels',
			OffensiveDuels: 'Offensive Duels',
			BackPasses: 'Back Passes',
			ForwardPasses: 'Forward Passes',
			VerticalPasses: 'Vertical Passes',
			ShotAssists: 'Shot Assists',
			BlockedShots: 'Blocked Shots',
			Crosses: 'Crosses',
			FoulsSuffered: 'Fouls Suffered',
			Dribbles: 'Dribbles',
			ReceivedPasses: 'Received Passes',
			Losses: 'Losses',
			AttackingActions: 'Attacking Actions',
			DefensiveActions: 'Defensive Actions',
			KeywordSearch: 'Keyword Search',
			ClearFilters: 'Clear Filters',
			Name: 'Name',
			Surname: 'Surname',
			Club: 'Club',
			Fee: 'Fee',
			State: 'State',
			Activity: 'Activity',
			Showing: 'Showing',
			to: 'to',
			To: 'To',
			of: 'of',
			SelectanAction: 'Select an Action',
			SendEmail: 'Send Email',
			AssignGroup: 'Assign Group',
			DetachGroup: 'Detach Group',
			EmailEditor: 'Email Editor',
			SelectGroup: 'Select Group',
			Choosed: 'Choosed',
			Choose: 'Choose',
			PaymentMethod: 'Payment Method',
			CreditDebitCard: 'Credit/Debit card',
			Continue: 'Continue',
			Noemailsfound: 'No emails found.',
			Address: 'Address',
			Subject: 'Subject',
			Date: 'Date',
			DeleteEmails: 'Delete Emails',
			Nouserschosen: 'No users chosen.',
			Noemailschosen: 'No emails chosen.',
			Contactus: 'Contact us',
			Insertmessage: 'Insert message',
			SelectRecipient: 'Select Recipient',
			UserData: 'User Data',
			Code: 'Code',
			Phonenumber: 'Phone number',
			Change: 'Change',
			Olde: 'Old',
			Newe: 'New',
			Confirm: 'Confirm',
			Confirmation: 'Confirmation',
			Language: 'Language',
			Yearly: 'Yearly',
			fee: 'fee',
			Membership: 'Membership',
			MemberFrom: 'Member From',
			member: 'member',
			Active: 'Active',
			Inactive: 'Inactive',
			Active: 'active',
			Paid: 'Paid',
			Unpaid: 'Unpaid',
			Notregistered: 'Not registered',
			Create: 'CREATE',
			Account: 'ACCOUNT',
			Register: 'Register',
			RegisterV: 'REGISTER',
			ConfirmPassword: 'Confirm Password',
			Youraccountisregisteredundername: 'Your account is registered under name:',
			andemail: 'and we have sent verify link on your email:',
			Alreadyaccount: 'Already have account',
			GlobalNews: 'Global News',
			SelectaRole: 'Select a Role',
			Generate: 'Generate',
			Inordertoviewyourstatistics: 'In order to view your statistics, you need to select the desired match first.',
			PERSONAL: 'PERSONAL',
			OnTarget: 'On Target',
			OffTarget: 'Off Target',
			Successful: 'Successful',
			Failed: 'Failed',
			Other: 'Other',
			ThisSeason: 'This season',
			WeProtectIntro: 'We protect your football interests',
			WelcomeIntro: 'Welcome to the official app of the Union of Football Professionals in Slovakia.',
		},
		validations: {
			required: "This field is required.",
			email: "Please enter a valid email address.",
			minLength: `Minimum length is ${minLength} characters`,
			sameAs: "Passwords don't match"
		},
		},
		sk: {
		message: {
			myboard: 'Nástenka',
			stats: 'Štatistiky',
			match: 'Zápas',
			player: 'Hráč',
			Documents: 'Dokumenty',
			users: 'Používatelia',
			usersov: 'Používateľov',
			allUsers: 'Zoznam Používateľov',
			addNewUser: 'Pridať Používateľa',
			ufpNews: 'Správy UFP',
			Emails: 'Emaily',
			emailov: 'emailov',
			Footballnews: 'Futbalové správy',
			NewsRumors: 'Správy a Novinky',
			Settings: 'Nastavenia',
			Groups: 'Skupiny',
			Products: 'Produkty',
			Surveys: 'Dotazníky',
			Contact: 'Kontakt',
			ForgotPassword: 'Zabudnuté heslo',
			Login: 'Prihlásenie',
			LoginV: 'PRIHLÁSIŤ',
			Submit: 'Poslať',
			Password: 'Heslo',
			password: 'heslo',
			ForgotPasswordNotice: 'Vložte sem Váš prihlasovací email, na ktorý pošleme link pre reset hesla.',
			EmailRequired: 'Email je potrebný.',
			EmailNotValid: 'Email nie je platný.',
			UpdatePassword: 'Zmena hesla.',
			NewPassword: 'Nové heslo',
			ConfirmNewPassword: 'Potvrdenie nového hesla',
			PickAPassword: 'Výber hesla',
			Suggestions: 'Návrhy',
			Atleast: 'Aspoň',
			oneIt: 'jedno',
			lowercase: 'malé písmeno',
			uppercase: 'veľké písmeno',
			numeric: 'číslo',
			characters: 'písmen',
			Update: 'Aktualizovať',
			Nonewemails: 'Žiadne nové správy',
			Inbox: 'Schránka',
			Profile: 'Profil',
			Wallet: 'Peňaženka',
			Logout: 'Odhlásenie',
			MatchStats: 'Zápasové štatistiky',
			Season: 'Sezóna',
			Match: 'Zápas',
			SelectMatch: 'Vyberte Zápas',
			SelectSeason: 'Vyberte Sezónu',
			Playerstats: 'Štatistiky hráča',
			Matches: 'Zápasy',
			Minutesplayed: 'Odohrané minúty',
			Goals: 'Góly',
			Yellowcards: 'Žlté karty',
			Redcards: 'Červené karty',
			LINEUPS: 'ZOSTAVY',
			STATS: 'ŠTATISTIKY',
			TEAM: 'TÍM',
			Substitutions: 'Náhradníci',
			BallPossession: 'Držanie lopty',
			Shotsontarget: 'Strely na bránu',
			Completedpasses: 'Prihrávky',
			TotalAttempts: 'Strely',
			Fouls: 'Fauly',
			Corners: 'Rohy',
			Offsides: 'Ofsajdy',
			Freekicks: 'Voľné kopy',
			Successfulduels: 'Úspešné súboje',
			Totallooses: 'Straty',
			Successfulpasses: 'Úspešné prihrávy',
			Shots: 'Strely',
			Duels: 'Súboje',
			Passes: 'Prihrávky',
			AerialDuels: 'Vzdušné súboje',
			DefensiveDuels: 'Defenzívne súboje',
			OffensiveDuels: 'Ofenzívne súboje',
			BackPasses: 'Prihrávky dozadu',
			ForwardPasses: 'Prihrávky dopredu',
			VerticalPasses: 'Vertikálne prihrávky',
			ShotAssists: 'Assistencie k strele',
			BlockedShots: 'Zblokované strely',
			Crosses: 'Centrované lopty',
			FoulsSuffered: 'Inkasované fauly',
			Dribbles: 'Driblingy',
			ReceivedPasses: 'Prijaté prihrávky',
			Losses: 'Straty',
			AttackingActions: 'Útočné akcie',
			DefensiveActions: 'Obranné akcie',
			KeywordSearch: 'Vyhľadať',
			ClearFilters: 'Vyčistiť filter',
			Name: 'Meno',
			Surname: 'Priezvisko',
			Club: 'Klub',
			Fee: 'Členské',
			State: 'Stav',
			Activity: 'Aktivita',
			Showing: 'Zobrazených',
			to: 'až',
			To: 'Komu',
			of: 'z',
			SelectanAction: 'Vyberte akciu',
			SendEmail: 'Poslať email',
			AssignGroup: 'Priradiť skupinu',
			DetachGroup: 'Odobrať skupinu',
			EmailEditor: 'Editor emailov',
			SelectGroup: 'Vyberte skupinu',
			Choosed: 'Vybraní',
			Choose: 'Vyberte',
			PaymentMethod: 'platobnú metódu',
			CreditDebitCard: 'Kreditná/Debetná karta',
			Continue: 'Pokračovať',
			Noemailsfound: 'Nenašli sa žiadne emaily.',
			Address: 'Adresa',
			Subject: 'Subjekt',
			Date: 'Dátum',
			DeleteEmails: 'Zmazať emaily',
			Nouserschosen: 'Žiadni vybratí užívatelia',
			Noemailschosen: 'Žiadne vybraté emaily.',
			Contactus: 'Kontaktujte nás',
			Insertmessage: 'Vložte správu',
			SelectRecipient: 'Vyberte príjemcu',
			UserData: 'Udaje o používateľovi',
			Code: 'Predvoľba',
			Phonenumber: 'Tel. číslo',
			Change: 'Zmeniť',
			Olde: 'Staré',
			Newe: 'Nové',
			Confirm: 'Potvrdite',
			Confirmation: 'Potvrdenie',
			Language: 'Jazyk',
			Yearly: 'Ročný',
			fee: 'poplatok',
			Membership: 'Členstvo',
			MemberFrom: 'Člen od',
			member: 'člen',
			Active: 'Aktívny',
			Inactive: 'Neaktívny',
			Paid: 'Uhradené',
			Unpaid: 'Neuhradené',
			Notregistered: 'Nie ste registrovaní',
			Create: 'VYTVORIŤ',
			Account: 'ÚČET',
			Register: 'Registrácia',
			RegisterV: 'REGISTROVAŤ',
			ConfirmPassword: 'Potvrdiť heslo',
			Youraccountisregisteredundername: 'Váš účet je zaregistrovaný pod menom:',
			andemail: 'a poslali sme potvrdzovací link na Váš email:',
			Alreadyaccount: 'Máte už účet',
			GlobalNews: 'Správy zo sveta',
			SelectaRole: 'Vyberte rolu',
			Generate: 'Generovať',
			Inordertoviewyourstatistics: 'Pre zobrazenie štatistík je potrebné vybrať zápas.',
			PERSONAL: 'OSOBNÉ',
			OnTarget: 'Na bránu',
			OffTarget: 'Mimo brány',
			Successful: 'Úspešné',
			Failed: 'Neúspešné',
			Other: 'Ďalšie',
			ThisSeason: 'Aktuálna sezóna',
			WeProtectIntro: 'Chránime Vaše futbalové záujmy.',
			WelcomeIntro: 'Vitajte na stránke oficiálnej aplikácie Únie Futbalových profesionálov Slovenska',
		},
		validations: {
			required: "Toto pole je nevyhnutné.",
			email: "Vložte platný email.",
			minLength: `Minimálna dĺžka je ${minLength} znakov`,
			sameAs: `Heslá sa nezhodujú`,
		},
		}
	}
  } */